eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 5000
spring:
  application:
    name: zuul-gateway
zuul:
  routes:
    zuulclientapi:
      path: /zuulclientapi/**
      serviceId: zuul-client
