eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 5000
spring:
  application:
    name: zuul-gateway
zuul: # 构建路由地址
  routes:
    zuulclientapi:
      path: /api/v2/**  # 匹配的路由规则
      serviceId: service-provider # 路由的目标服务名
