server:
  port: 8082
spring:
  application:
    name: ELK-KAFKA-SERVICE-C
  devtools:
    restart:
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


