server:
  port: 8080
spring:
  application:
    name: ELK-KAFKA-SERVICE-A
  devtools:
    restart:
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
